/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mappingdocumentation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author dmitryrassakhatsky
 */
public
        class Form extends javax.swing.JFrame {

    public
            String pathName = null;
    public
            String outName = null;
    public
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    public
            int w = (dim.width);
    public
            int h = (dim.height);

    /**
     * Creates new form Form
     */
    public
            Form() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        jDialog2 = new javax.swing.JDialog();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        jDialog3 = new javax.swing.JDialog();
        label2 = new java.awt.Label();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDialog4 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jFileChooser1.setCurrentDirectory(new java.io.File("/"));
        jFileChooser1.setBounds(new java.awt.Rectangle(300, 200, 0, 0));

        jDialog1.setTitle("Completed");
        jDialog1.setBounds(new java.awt.Rectangle(300, 200, 300, 200));
        jDialog1.setIconImage(null);
        jDialog1.setMinimumSize(new java.awt.Dimension(300, 200));

        label1.setText("Mission Accomplished!");

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .add(label1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jDialog2.setTitle("Please, choose target file.");
        jDialog2.setLocation(new java.awt.Point(300, 200));
        jDialog2.setSize(new java.awt.Dimension(400, 100));

        textField1.setText("textField1");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        button1.setActionCommand("Ok");
        button1.setLabel("Ok");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jDialog2Layout = new org.jdesktop.layout.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(button1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(button1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jDialog3.setTitle("Completed");
        jDialog3.setBounds(new java.awt.Rectangle(300, 200, 300, 200));
        jDialog3.setIconImage(null);
        jDialog3.setMinimumSize(new java.awt.Dimension(300, 200));

        label2.setText("Sorry, such file doesn't exist...");

        org.jdesktop.layout.GroupLayout jDialog3Layout = new org.jdesktop.layout.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .add(label2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .add(label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jFrame1.setLocation(new java.awt.Point(200, 300));
        jFrame1.setMinimumSize(new java.awt.Dimension(400, 300));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jDialog4.setMinimumSize(new java.awt.Dimension(375, 390));

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jTextArea2.setText("Инструкция:\n1) Открыть Message Mapping\n2) Выбрать \"Text Preview\"\n3) Скопировать Text Preview\n4) Создать TXT файл с Text Preview\n5) Выбрать файл с помощью кнопки \"Choose File\"\n6) Выбрать имя файла-результата\n7) Enjoy!\n\nInstruction:\n1) Открыть Message Mapping\n2) Выбрать \"Text Preview\"\n3) Скопировать Text Preview\n4) Создать TXT файл с Text Preview\n5) Выбрать файл с помощью кнопки \"Choose File\"\n6) Выбрать имя файла-результата\n7) Enjoy!\n\n:\n1) Открыть Message Mapping\n2) Выбрать \"Text Preview\"\n3) Скопировать Text Preview\n4) Создать TXT файл с Text Preview\n5) Выбрать файл с помощью кнопки \"Choose File\"\n6) Выбрать имя файла-результата\n7) Enjoy!\n\n");
        jTextArea2.setMinimumSize(new java.awt.Dimension(350, 400));
        jScrollPane2.setViewportView(jTextArea2);

        org.jdesktop.layout.GroupLayout jDialog4Layout = new org.jdesktop.layout.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Please, choose a file...");
        setBounds(new java.awt.Rectangle(400, 300, 0, 0));

        jButton1.setText("Close App");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Choose File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Help");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .add(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private//GEN-FIRST:event_jButton1ActionPerformed
            void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-HEADEREND:event_jButton1ActionPerformed
        /**
         * Завершение работы программы
         */
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private//GEN-FIRST:event_button1ActionPerformed
            void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-HEADEREND:event_button1ActionPerformed
        MappingDocumentation mappingDocumentation = new MappingDocumentation();
        jDialog2.setVisible(false);
        outName = textField1.getText();
        try {
            mappingDocumentation.execute(pathName, outName);
            jDialog1.setLocation((w - jDialog1.getSize().width) / 2, (h - jDialog1.getSize().height) / 2);
            jDialog1.setVisible(true);
            try {
                Thread.sleep(2000L);
                jDialog1.setVisible(false);
            }
            catch (InterruptedException ex) {
                Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (Exception ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);

            jTextArea1.setEditable(false);
            jTextArea1.append(ex.getMessage());
            jTextArea1.append("\n");
            StackTraceElement[] ste = ex.getStackTrace();
            for (int i = 0; i < ste.length; i++) {
                jTextArea1.append(ste[i].toString());
                jTextArea1.append("\n");
            }
            jFrame1.setLocation((w - jFrame1.getSize().width) / 2, (h - jFrame1.getSize().height) / 2);
            jFrame1.setVisible(true);
        }
    }//GEN-LAST:event_button1ActionPerformed

    private//GEN-FIRST:event_textField1ActionPerformed
            void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-HEADEREND:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private//GEN-FIRST:event_jButton2ActionPerformed
            void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-HEADEREND:event_jButton2ActionPerformed
        JFileChooser chooser = null;
        chooser = new JFileChooser();
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {    // JFileChooser.APPROVE_OPTION
            File file = jFileChooser1.getSelectedFile();

            pathName = file.toString();
            outName = pathName.substring(0, pathName.lastIndexOf("/") + 1) + "out.csv";
            if (!file.exists()) {
                jDialog3.setLocation((w - jDialog3.getSize().width) / 2, (h - jDialog3.getSize().height) / 2);
                jDialog3.setVisible(true);
                try {
                    Thread.sleep(2000);
                    jDialog3.setVisible(false);
                }
                catch (InterruptedException ex) {
                    Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                jDialog2.setLocation((w - jDialog2.getSize().width) / 2, (h - jDialog2.getSize().height) / 2);
                jDialog2.setVisible(true);
                textField1.setText(outName);
            }


        }    }//GEN-LAST:event_jButton2ActionPerformed

    private//GEN-FIRST:event_jButton3ActionPerformed
            void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-HEADEREND:event_jButton3ActionPerformed
        jDialog4.setLocation((w - jDialog2.getSize().width) / 2, (h - jDialog2.getSize().height) / 2);
        String rus = "Инструкция:\n1) Открыть Message Mapping\n2) Выбрать \"Text Preview\"\n3) Скопировать Text Preview\n4) Создать TXT файл с Text Preview\n5) Выбрать файл с помощью кнопки \"Choose File\"\n6) Выбрать имя файла-результата\n7) Enjoy!";
        String eng = "Instruction:\n1) Open you Message Mapping\n2) Choose\"Text Preview\"\n3) Copy Text Preview text\n4) Create text file (like .txt) with Text Preview\n5) Use \"Choose File\" button for choosing your file\n6) Write filename for result, it will be create in same path\n7) Enjoy!";
        jTextArea2.setText(rus+"\n\n"+eng+"\n\n\n\n\nAsk your question to @satkacity");
        jDialog4.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public
                    void run() {
                new Form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
